### ISSUE TITLE
Feature: Manifest URLs

### ISSUE THREAD

**Issue by MGatner** [tattersoftware/codeigniter4-assets#14]
Allow source field in manifests to be a URL for CDN harvesting.

**Comment by evansharp** [comment]
This is a big one for this library to accomplish its goal. I'd say 60% of my 'assets' are typically CDN hosted.

**Comment by MGatner** [comment]
The `Manifests` function of this library will most likely be moving to another library or maybe even a framework component. On that list is support for remote sources. I think your use case is pretty common, additionally a lot of "Get Started" guides only have their CDN available (e.g. https://getbootstrap.com/docs/5.0/getting-started/introduction/) so it will be easier when those can be pasted right in.

**Comment by MGatner** [comment]
This will be handled by the framework's `Publisher` now.
