### ISSUE TITLE
vendor js loaded after route assets

### ISSUE THREAD

**Issue by rodolfodn** [tattersoftware/codeigniter4-assets#4]
<script src="http://localhost:8080/assets/footer.js?v=1575209932" type="text/javascript"></script>
<script src="http://localhost:8080/assets/test/test.js?v=1575210266" type="text/javascript"></script>
<script src="http://localhost:8080/assets/vendor/jquery/jquery.min.js?v=1575151520" type="text/javascript"></script>
<script src="http://localhost:8080/assets/vendor/bootstrap/bootstrap.bundle.min.js?v=1575151520" type="text/javascript"></script>

![image](https://user-images.githubusercontent.com/5527054/69915533-f635e600-142e-11ea-8e85-0bf43dd114ea.png)

**Comment by MGatner** [comment]
I’ll take a look. User routes should definitely take precedence (e.g. load after) vendor assets.

**Comment by rodolfodn** [comment]
I've fixed. But I don't know why I can't make a separated pull request from the other one.

The issue was on Assets.php line 173. The array merge was inverted.

**Comment by MGatner** [comment]
When making pull requests you should make your own local branch (like “bugfix-locale”) and apply your commits there so when you want to make a second PR you can branch off the unmodified `develop` again. 

I’ve merged your first PR so feel free to submit another now if you have it. Thank you for the work.

**Comment by rodolfodn** [comment]
Thanks!
The fix for this one is on the merge already.
You can close the issue.
