### ISSUE TITLE
Issue: Outputted URIs contain \ backslash on Windows

### ISSUE THREAD

**Issue by craigrodway** [tattersoftware/codeigniter4-assets#48]
Hi!

Given the code:

```php
<?= \Tatter\Assets\Asset::createFromPath('main.css') ?>
<?= \Tatter\Assets\Asset::createFromPath('main.js') ?>
```

It now produces:

```html
<link href="http://example.com/assets\main.css?v=1644518679" rel="stylesheet" type="text/css" />
<script src="http://example.com/assets\main.js?v=1644518679" type="text/javascript"></script>
```

While it does seem to work, and browsers are very forgiving, it's not correct.

I think the issue is here: https://github.com/tattersoftware/codeigniter4-assets/blob/develop/src/Asset.php#L57

```php
self::$config->uri       = rtrim(self::$config->uri, '/\\') . DIRECTORY_SEPARATOR;
```

This line should probably revert back to a simple '/' value instead of DIRECTORY_SEPARATOR.

**Comment by MGatner** [comment]
You are very right. I had some issues on Windows and did a pretty global application of `DIRECTORY_SEPARATOR`, must have accidentally scooped this one up! Care to send a PR?

**Comment by craigrodway** [comment]
No worries, all done! :)

**Comment by MGatner** [comment]
Thanks for that! Quick and clean fix. I'm traveling but will release this bugfix when I'm home.
