### ISSUE TITLE
{locale} support

### ISSUE THREAD

**Issue by rodolfodn** [tattersoftware/codeigniter4-assets#5]
The current version do not support localised uris.

![image](https://user-images.githubusercontent.com/5527054/69915580-71979780-142f-11ea-94a2-69d17d839351.png)

![image](https://user-images.githubusercontent.com/5527054/69915584-765c4b80-142f-11ea-8119-ffa7dc31aa1a.png)

**Comment by MGatner** [comment]
I’m not sure it is a given that the desired behavior is locale-specific assets. By default the library will use `uri_string()` if none is specified, so maybe that is trimming the locale? I will look into possible solutions but you can also always specific the route to be used with `Assets->setRoute()`

**Comment by rodolfodn** [comment]
Well, I've made a pull request with my possible solution.

**Comment by MGatner** [comment]
Thanks! I’m mobile now but I’ll check it out ASAP

**Comment by MGatner** [comment]
Resolved by #6
