### ISSUE TITLE
In readme small fix word

### ISSUE THREAD

**Issue by neznaika0** [tattersoftware/codeigniter4-assets#56]
Hi. On readme page small fix word "assset":
`echo view('main', ['assset' => $asset]);`

**Comment by MGatner** [comment]
Good catch! Would you like to open a Pull Request? If you haven't done one before you can do it directly in GitHub: navigate to the file and click "Edit". It will prompt you to make a fork and branch and walk you through creating the PR, then you will count as a contributor.

**Comment by neznaika0** [comment]
Ok, PR send https://github.com/tattersoftware/codeigniter4-assets/pull/57
