### ISSUE TITLE
Configure routes dynamically

### ISSUE THREAD

**Issue by barkdoll** [tattersoftware/codeigniter4-assets#7]
Awesome work on this project! 

So forgive my lack of understanding on this service library, but I was just wondering if it is possible to configure this dynamically.

The reason I ask is that I would like to use some logic to build the `$routes` property.

**Comment by MGatner** [comment]
Thanks for the interest! I’m open to suggestions and edits, but I don’t think I understand your question. It sounds like you are using the Assets library to load JS/CSS automatically based on the route. You want to build routes different than the default? You can always specify a route with `setRoute()` - does that help?

**Comment by MGatner** [comment]
`service('assets')->setRoute(‘my/custom/route’)->css();`

**Comment by barkdoll** [comment]
> Thanks for the interest! I’m open to suggestions and edits, but I don’t think I understand your question. It sounds like you are using the Assets library to load JS/CSS automatically based on the route. You want to build routes different than the default? You can always specify a route with `setRoute()` - does that help?

Thanks for pointing me to `setRoute()`. I think it's what I am looking for. I will test drive it a bit. I just have one question left. Is it possible for me to set multiple routes and combine asset route collections or would the last `setRoute()` call override any previous calls?

Example:
```php
service('assets')
  ->setRoute('custom/route')
  ->setRoute('extra/library/route')
  ->js();
```

**Comment by MGatner** [comment]
Currently the route is a single static entry, but there is nothing to prevent you from making separate calls for each route:
```
service('assets')->setRoute('custom/route')->js();
service(‘assets’)->setRoute('extra/library/route')->js();

**Comment by MGatner** [comment]
You might also want to leverage the config file, since it looks like you may be trying to replicate some of its function. There you can define as many explicit assets to load for whichever routes you want, regardless of the auto detection.

**Comment by barkdoll** [comment]
> Currently the route is a single static entry, but there is nothing to prevent you from making separate calls for each route:
> 
> ```
> service('assets')->setRoute('custom/route')->js();
> service(‘assets’)->setRoute('extra/library/route')->js();
> ```
> You might also want to leverage the config file, since it looks like you may be trying to replicate some of its function. There you can define as many explicit assets to load for whichever routes you want, regardless of the auto detection.

Awesome. This all helps a lot. Thanks so much bro.
