### ISSUE TITLE
config Assets.php for jquery e other

### ISSUE THREAD

**Issue by gragia79** [tattersoftware/codeigniter4-assets#8]
Good Morning,
I configured the library as described in the readme file.
I ran the command
php spark assets: publish
in the project root as indicated.
He made me folders
public / assets / vendor
bootstrap
jquery
dropzone
the question?
how should I configure the app / config / assets.php file
I don't understand the references to the files.
for bootstrap they are bootstrap / dist /
for jquery?
Thanks

**Comment by MGatner** [comment]
You need to define which routes will use the assets. If you want all routes the use `''` (empty string). See this one for example:

https://github.com/tattersoftware/sefer/blob/develop/app/Config/Assets.php

Once you have defined the route with its array of assets you can call the library from your view template/layout to inject the asset tags. See for example:

https://github.com/tattersoftware/sefer/blob/4c8e1beb389e30f03a3b717935fc1103b7498884/app/Views/layouts/public.php#L28

**Comment by gragia79** [comment]
ok i changed the path and upload the files correctly.
It loads everything inside my body.
even though I added
<Head>
        <?= service ('assets') -> css (); ?>
</ Head>
it's normal?

As for bootstrap to also load the folder of icons, how should you do it?
do I have to copy it manually?

**Comment by MGatner** [comment]
The CSS files should be loading in your `<head>` tag. It looks like you have it correct, except maybe for some spacing and capitalization, but I'm not sure that matters:
```
<html>
<head>         
   <?= service('assets')->css(); ?>
</head>
<body>
...
</body>
</html>
```

I'm not familiar with the Bootstrap icons, but you can modify the manifest file at **app/Manifests/Bootstrap.json** to include anything you want and then re-run `php spark assets:publish` to have them included in your public assets.

**Comment by gragia79** [comment]
thanks
