### ISSUE TITLE
loading single js per page

### ISSUE THREAD

**Issue by gragia79** [tattersoftware/codeigniter4-assets#9]
Good morning,
I would need to upload single js files to a specific page, but after loading the main js files.
example:
general for each page
`<? = service ('assets') -> js ()?>`
in assets.php does not include chart.js
single only for one page
`<? = service ('assets') -> tag ('vendor / chartjs / chart.js')?>`
this is possible?

**Comment by MGatner** [comment]
Yes, you have that right. Did you have a problem with doing it that way?

**Comment by gragia79** [comment]
yes, i don't know how to load chart.js after loading general js ().
i use this method:
view ( 'header');
view ( 'content');
view ( 'footer');
where footer has:
```
        <?php echo service('assets')->js() ?>
    </body>
</html>
```

**Comment by MGatner** [comment]
I’m not sure I understand. Your example in your original post should work just fine. Load all your configured assets with `js()` and then after that use the `tag()` command to load your single-page Chart.js:

`<?= service ('assets')->tag('vendor / chartjs / chart.js') ?>`

**Comment by gragia79** [comment]
Yes, but the footer remains the same for all pages.

While the content changes.
And in the content I load the individual js that serve on that page.

The problem is that first I have to load the basic js and then load the
single js.

For css it doesn't happen because I load first the css base then the single
css.

Although I noticed that: for css the flow is fine.
For js there is the problem of sequential positioning.
First js singole, and load the js base.
Header
    Css base
Content
     Css singol
     Js singol
Footer
      Js base
Thanks.


Il dom 16 feb 2020, 19:55 MGatner <notifications@github.com> ha scritto:

**Comment by MGatner** [comment]
Ahh okay I understand now! Yes I do the same thing. My solution is to define a view layout that displays the main content and the footer with the Assets service js(), then I have another section below that so each page can load its own JS:

`<?= $this->renderSection('footerAssets') ?>`

See an example layout: https://gitlab.oit.duke.edu/academic-technology/bluesmith/blob/develop/app/Views/layouts/public.php

An an example of injecting assets below the footer (not actually a script rage but could be): https://gitlab.oit.duke.edu/academic-technology/bluesmith/blob/develop/app/Views/account/job.php

**Comment by gragia79** [comment]
My proget.
Controller:
`echo view('W_Content', $data);`

Header: header.php
```
<!doctype html>
<html lang="en">
    <head>
        <title>Project</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <link rel="shortcut icon" type="image/png" href="/favicon.ico"/>
        <?php echo service('assets')->css(); 
        echo service('assets')->tag("css/Layout.css");
        ?>

    </head>
    <body>
```
Content: W_Content,php
```
<?php 
   echo view('header');
   echo service('assets')->tag("vendor/chartjs/chart.css");
   $this->renderSection('headerAssets');   
?>
<!-- HTML CONTENT -->
<?php
  echo service('assets')->tag("vendor/chartjs/chart.js");
    echo view('footer');
```
Footer:footer.php

```
   <?php echo service('assets')->js() ;
    $this->renderSection('footerAssets');
    ?>
    </body>
</html>
```
in service('assets')->js() and service('assets')->css() is isclude bootstrap,jquery global library used.

but it does not render assets.
that is, upload chart.js first.
then later jquery.
This is a problem for me because it has to load jquery first, and then chart.js.
Where am I doing wrong?
Thank you

**Comment by MGatner** [comment]
It looks like you aren’t actually leveraging View Layouts. Hard for me to tell on mobile, but read this section in the User Guide and I will look at it closer when I’m on a computer:

https://codeigniter4.github.io/CodeIgniter4/outgoing/view_layouts.html

**Comment by MGatner** [comment]
Sorry, just getting back to this. First issue is you aren't really using a Layout. Read the section linked above, but basically you need to create a layout view that looks something like this:
```
/* app/Views/layouts/public.php */

<html lang="en">
<head>
	<meta charset="utf-8">

	<?= service('assets')->css() ?>

	<?= service('assets')->tag('vendor/jquery/jquery.min.js') ?>
	
	<?= $this->renderSection('headerAssets') ?>
</head>
<body>
	<main role="main">
		<?= $this->renderSection('main') ?>
	</main>

	<?= service('assets')->js() ?>

	<?= $this->renderSection('footerAssets') ?>
</body>
</html>
```

Notice:

1. Forceful loading of JQuery first, in the `<head>` tag, to make sure it is loaded before everything else
2. Optional sections `headerAssets` and `footerAssets` in case a page needs to add its own tags that you want to handle separate from the module
3. Header and footer have standard `service('assets')->css()` and `service('assets')->js()` respectively.

Then in your view you would extend the layout:
```
/* app/Views/welcome.php */

<?= $this->extend('layouts/public') ?>
<?= $this->section('main') ?>
	<h3>Hello world</h3>
<?= $this->endSection() ?>
<?= $this->section('footerAssets') ?>
	<script>
		// Some JavaScript for this view only
	</script>
<?= $this->endSection() ?>
```

**Comment by gragia79** [comment]
Thanks.
